language: python
cache: pip
python:
#  - "3.6"
#  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - bash ./run-ci.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
